[workspace]
members = ["app", "crates/config", "crates/selector", "crates/proxy"]
default-members = ["app"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
my_config = { path = "crates/config" }
my_selector = { path = "crates/selector" }
my_proxy = { path = "crates/proxy" }
anyhow = "1.0.104"
arc-swap = "1.9.2"
bytes = "1.12.1"
chrono = "0.4.45"
flate2 = "1.1.10"
futures-util = { version = "0.3.34", default-features = false, features = [
  "std",
] }
http = "1.5.0"
http-body-util = "0.1.5"
hyper = { version = "1.11.1", features = ["full"] }
hyper-rustls = { version = "0.27.10", default-features = false, features = [
  "http1",
  "http2",
  "tls12",
  "aws-lc-rs",
  "webpki-roots",
] }
hyper-util = { version = "0.1.20", features = ["full"] }
mimalloc = { version = "0.1.52", features = ["v2", "no_thp", "override"] }
notify = "8.2.0"
salvo = { version = "1.0.0", default-features = false, features = [
  "server",
  "http1",
  "http2",
  "oapi",
  "affix-state",
  "test",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
taplo = "0.14.0"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "local-time",
  "env-filter",
] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
expect_used = { level = "warn", priority = -1 }
similar_names = "allow"
missing_errors_doc = "allow"
missing_safety_doc = "allow"
missing_panics_doc = "allow"
cast_precision_loss = "allow"
struct_excessive_bools = "allow"

[profile.dev]
debug = 0
debug-assertions = true
incremental = true
panic = "abort"

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "thin"
opt-level = 2
strip = true
debug = 0
debug-assertions = false
incremental = false
panic = "abort"
